// Regenerates src/platform/theme-fallback.css from the installed Bloom.
//
// Run: bun run generate:theme-fallback
//
// WHY THIS IS GENERATED, and not the hand-written :root/.dark block the other
// Oxy Vite apps carry: Bloom stopped hand-authoring its palettes. Every token
// is now derived by its colour engine from a preset seed, and `getPresetVars`
// is documented as the single source of truth that "consumer apps must not
// redefine". A copied block is a fork of the design system that nothing checks
// -- measured against @oxyhq/bloom 0.87.0, the block in
// OxyHQServices/packages/test-app-vite is a different palette in a different
// colour space (oklch approximations vs the engine's resolved rgb()), so
// copying it would have shipped the wrong brand colours to every Astro page.
//
// What the emitted file is FOR: the frame between the document painting and
// BloomThemeProvider writing its vars onto document.documentElement. The
// provider writes them in a layout effect, so in practice that frame is short
// -- but with no definition at all, `background: var(--background)` is
// transparent, and a page that fails to boot has no colours to fail with.
//
// Bloom's provider always wins at runtime: it writes inline custom properties
// on the root element, which outrank any :root rule here.

import {writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

// Bloom's own token resolver, from its narrow `./preset-vars` export rather
// than the `./theme` barrel: the barrel reaches react-native, whose Flow-typed
// entry no Node-side runtime parses, while this module is pure colour maths.
import {getPresetVars} from '@oxyhq/bloom/preset-vars';

/** The preset a page falls back to before the browser reports the user's. */
const FALLBACK_PRESET = 'oxy';

function block(selector: string, tokens: Record<string, string>, indent: string): string {
  const body = Object.entries(tokens)
    .map(([name, value]) => `${indent}  ${name}: ${value};`)
    .join('\n');
  return `${indent}${selector} {\n${body}\n${indent}}`;
}

const light = getPresetVars(FALLBACK_PRESET, 'light');
const dark = getPresetVars(FALLBACK_PRESET, 'dark');

const css = `/*
 * AUTO-GENERATED by scripts/generate-theme-fallback.ts -- DO NOT EDIT.
 *
 * Bloom's "${FALLBACK_PRESET}" preset, resolved through @oxyhq/bloom's own
 * getPresetVars(). Regenerate after bumping @oxyhq/bloom:
 *
 *   cd webui/app && bun run generate:theme-fallback
 *
 * These values cover the frame before BloomThemeProvider writes the user's
 * real theme onto the document root, where they are outranked by the
 * provider's inline custom properties.
 */

${block(':root', light, '')}

/* The user agent's scheme, for the frame before the browser reports the
   configured one. \`.light\` is Bloom's explicit-light marker and must not be
   overridden by the media query. */
@media (prefers-color-scheme: dark) {
${block(':root:not(.light)', dark, '  ')}
}

/* Bloom's explicit dark marker, written onto the document root by
   applyDarkClass(). */
${block(':root.dark', dark, '')}
`;

const outPath = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../src/platform/theme-fallback.css',
);
writeFileSync(outPath, css);
process.stdout.write(`wrote ${outPath} (${Object.keys(light).length} tokens per scheme)\n`);
