// Astro's palette, asked of Bloom and emitted for both surfaces at once.
//
// Astro paints two things from the same brand: Chromium's native UI, which
// reads colours from a C++ ColorProvider (1,588 colour ids -- frame, tabs,
// omnibox, menus), and its WebUI pages, which read CSS custom properties. They
// share nothing in Chromium's own design.
//
// Deriving Bloom's palette twice -- once by hand into C++ and once into CSS --
// is how the two drift, and a drift here is invisible until someone puts the
// browser frame next to a settings card. So both artefacts come from ONE call
// to Bloom's own getPresetVars, and a test asserts they agree.
//
// Usage: bun run generate.mjs --preset oxy --out-header X.h --out-css Y.css

import {getPresetVars} from '@oxyhq/bloom/preset-vars';
import {writeFileSync, mkdirSync} from 'node:fs';
import {dirname} from 'node:path';

function parseArgs(argv) {
  const args = {preset: 'oxy'};
  for (let i = 0; i < argv.length; i += 2) {
    const key = argv[i]?.replace(/^--/, '');
    const value = argv[i + 1];
    if (!key || value === undefined) {
      throw new Error(`expected --key value pairs, got ${argv.slice(i).join(' ')}`);
    }
    args[key.replace(/-([a-z])/g, (_, c) => c.toUpperCase())] = value;
  }
  return args;
}

/** `rgb(144 61 170)` -> `{r: 144, g: 61, b: 170}`. */
function parseRgb(value) {
  const m = value.match(/rgb\(\s*(\d+)[\s,]+(\d+)[\s,]+(\d+)/);
  if (!m) {
    // Not a soft failure: a colour that silently fails to parse would be
    // emitted as black and look like a deliberate choice.
    throw new Error(`cannot parse colour ${value}`);
  }
  return {r: +m[1], g: +m[2], b: +m[3]};
}

// The variables both surfaces need. Deliberately a short list rather than all
// 58: every entry here becomes a colour somebody has to keep looking right in
// two places, so it grows only when a surface actually needs it.
const WANTED = [
  'primary', 'primary-foreground',
  'background', 'foreground',
  'card', 'card-foreground',
  'border', 'muted', 'muted-foreground',
  'accent', 'accent-foreground',
];

function collect(preset) {
  const out = {};
  for (const mode of ['light', 'dark']) {
    const vars = getPresetVars(preset, mode);
    out[mode] = {};
    for (const name of WANTED) {
      const value = vars[`--${name}`];
      if (value === undefined) {
        throw new Error(
            `Bloom's ${preset}/${mode} preset has no --${name}. ` +
            `The preset's variable set has changed; update WANTED rather ` +
            `than defaulting, so a missing colour is a build failure and not ` +
            `a black surface.`);
      }
      out[mode][name] = parseRgb(value);
    }
  }
  return out;
}

function toSymbol(name) {
  return 'kAstro' + name.split('-').map(p => p[0].toUpperCase() + p.slice(1)).join('');
}

function emitHeader(palette, preset) {
  const lines = [
    '// Generated by //astro/browser/resources/palette/generate.mjs.',
    '// Do not edit: regenerate from Bloom rather than adjusting a value here.',
    '//',
    `// Bloom preset: ${preset}. The same call also emits the CSS the WebUI`,
    '// pages use, so the browser frame and a settings card cannot drift apart.',
    '',
    '#ifndef ASTRO_BROWSER_UI_COLOR_ASTRO_PALETTE_H_',
    '#define ASTRO_BROWSER_UI_COLOR_ASTRO_PALETTE_H_',
    '',
    '#include "third_party/skia/include/core/SkColor.h"',
    '',
    'namespace astro {',
    '',
  ];
  for (const mode of ['light', 'dark']) {
    const suffix = mode === 'dark' ? 'Dark' : 'Light';
    lines.push(`// ${mode} mode`);
    for (const [name, c] of Object.entries(palette[mode])) {
      lines.push(`inline constexpr SkColor ${toSymbol(name)}${suffix} =`);
      lines.push(`    SkColorSetRGB(0x${c.r.toString(16).padStart(2, '0')}, ` +
                 `0x${c.g.toString(16).padStart(2, '0')}, ` +
                 `0x${c.b.toString(16).padStart(2, '0')});`);
    }
    lines.push('');
  }
  lines.push('}  // namespace astro', '',
             '#endif  // ASTRO_BROWSER_UI_COLOR_ASTRO_PALETTE_H_', '');
  return lines.join('\n');
}

function emitCss(palette, preset) {
  const lines = [
    '/* Generated by //astro/browser/resources/palette/generate.mjs.',
    ' * Do not edit: regenerate from Bloom rather than adjusting a value here.',
    ' *',
    ` * Bloom preset: ${preset}. The same call emits the C++ palette the native`,
    ' * UI is painted from, so a settings card and the browser frame around it',
    ' * cannot drift apart. */',
    '',
    '/* #css_wrapper_metadata_start',
    ' * #type=style',
    ' * #css_wrapper_metadata_end */',
    '',
    'html {',
  ];
  for (const [name, c] of Object.entries(palette.light)) {
    lines.push(`  --astro-${name}: rgb(${c.r} ${c.g} ${c.b});`);
  }
  lines.push('}', '', '@media (prefers-color-scheme: dark) {', '  html {');
  for (const [name, c] of Object.entries(palette.dark)) {
    lines.push(`    --astro-${name}: rgb(${c.r} ${c.g} ${c.b});`);
  }
  lines.push('  }', '}', '');
  return lines.join('\n');
}

const args = parseArgs(process.argv.slice(2));
const palette = collect(args.preset);

for (const [path, text] of [[args.outHeader, emitHeader(palette, args.preset)],
                           [args.outCss, emitCss(palette, args.preset)]]) {
  if (!path) {
    continue;
  }
  mkdirSync(dirname(path), {recursive: true});
  writeFileSync(path, text, 'utf8');
  console.log(`  wrote ${path}`);
}
console.log(`  ${WANTED.length} colours x 2 modes, from Bloom's ${args.preset} preset`);
