#!/usr/bin/env bash
# The committed baseline must be what the tools produce today.
#
# This is the case that makes the rest of the baseline worth citing. Issue #6's
# closing criterion is "later issues can cite this baseline as their
# compatibility reference" — without a drift check that degrades to citing a
# snapshot nobody revalidated, which is worse than having no baseline at all,
# because it carries the authority of a document without the accuracy of one.

source "$(dirname "${BASH_SOURCE[0]}")/../lib/harness.sh"
harness::setup

GENERATE="$ASTRO_ROOT/tools/baseline/generate-all.sh"
BASELINE_DIR="$ASTRO_ROOT/docs/astro-next/baseline"
tmp="$(harness::tmpdir)"

harness::assert_file_exists "$GENERATE"

# --- The committed documents are current -------------------------------------

harness::run "$GENERATE" --check
harness::assert_status 0 "the committed baseline matches what the tools produce"
harness::assert_output_contains "Baseline is current" "confirmation"

# --- Drift is detected -------------------------------------------------------
#
# Mutate a committed document and prove the check fails and names it. A drift
# check nobody has seen fail is indistinguishable from one that cannot.

TARGET="$BASELINE_DIR/platform-matrix.md"
harness::assert_file_exists "$TARGET"
cp "$TARGET" "$tmp/pristine-platform-matrix.md"

printf '\n<!-- deliberate drift planted by the test suite -->\n' >> "$TARGET"

harness::run "$GENERATE" --check
harness::assert_nonzero_status "a modified baseline document"
harness::assert_output_contains "out of date" "names the problem"
harness::assert_output_contains "platform-matrix.md" "names the document"
harness::assert_output_contains "compatibility reference" "explains why it matters"

# --- A failed check leaves the tree exactly as it found it -------------------
#
# --check has to be safe to run against a working tree carrying unrelated
# uncommitted work, so on failure it must restore what it FOUND — which here is
# the drifted file, not the regenerated one. Restoring the regenerated content
# would silently "fix" a developer's uncommitted edit, and a check that edits
# your working tree is a check you stop running.

HARNESS_ASSERTIONS=$((HARNESS_ASSERTIONS + 1))
if ! grep -q 'deliberate drift planted by the test suite' "$TARGET"; then
    cp "$tmp/pristine-platform-matrix.md" "$TARGET"
    harness::fail "--check overwrote the working tree with regenerated content"
fi

# Now put the document back and confirm the tree is genuinely current again, so
# this case cannot leave a later run failing for a reason it created itself.
cp "$tmp/pristine-platform-matrix.md" "$TARGET"
harness::assert_files_identical "$tmp/pristine-platform-matrix.md" "$TARGET"

harness::run "$GENERATE" --check
harness::assert_status 0 "baseline is current again after the drift test"

# --- Every generated document declares its generator -------------------------
#
# A generated file that does not say so gets hand-edited, and the next --check
# reverts the edit with no explanation.

HARNESS_ASSERTIONS=$((HARNESS_ASSERTIONS + 1))
generated=0
while IFS= read -r document; do
    generated=$((generated + 1))
    if ! head -3 "$document" | grep -q 'Generated by tools/baseline/'; then
        harness::fail "$(basename "$document") does not declare which tool generates it"
    fi
done < <(grep -rl 'Generated by tools/baseline/' "$BASELINE_DIR")

if [ "$generated" -lt 4 ]; then
    harness::fail "only $generated generated document(s) found; expected the full set"
fi

harness::pass
