// Copyright 2026 Oxy. All rights reserved.
// Use of this source code is governed by a BSD-style license.

#include "chrome/browser/oxy/webui/astro_webui_page.h"

#include <string>
#include <utility>

#include "base/files/file_path.h"
#include "base/files/file_util.h"
#include "base/functional/bind.h"
#include "base/logging.h"
#include "base/memory/ref_counted_memory.h"
#include "base/path_service.h"
#include "base/strings/escape.h"
#include "base/strings/strcat.h"
#include "content/public/browser/browser_context.h"
#include "content/public/browser/web_contents.h"
#include "content/public/browser/web_ui.h"
#include "content/public/browser/web_ui_data_source.h"
#include "content/public/common/url_constants.h"
#include "services/network/public/mojom/content_security_policy.mojom.h"

namespace astro {

namespace {

// The document a request resolves to when it names no file of its own. An
// Astro page is a single-page app: every route it owns is served by the same
// document and routed client-side.
constexpr char kIndexDocument[] = "index.html";

// Strips the query and fragment a WebUI request can still carry, and refuses
// anything that could climb out of the resource directory.
//
// Returns false for a path that must not be served. A traversal attempt is a
// refusal, never a normalisation: silently rewriting `../../etc/passwd` into
// something servable is how a path check becomes a path bug.
bool ResolveRequestPath(const std::string& requested, std::string* out) {
  std::string path = requested.substr(0, requested.find_first_of("?#"));
  if (path.empty()) {
    path = kIndexDocument;
  }
  if (path.find("..") != std::string::npos || path.front() == '/') {
    return false;
  }
  *out = std::move(path);
  return true;
}

// A page that says what is missing, instead of a blank one that does not.
//
// Astro deleted a settings surface that rendered blank with no error when its
// asset directory was absent; this is the shape that condemned it. The body is
// deliberately plain HTML with no script and no external reference, so it
// renders under the page's own CSP whatever that page declared.
std::string MissingResourceDocument(std::string_view host,
                                    const base::FilePath& path) {
  return base::StrCat({
      "<!doctype html><meta charset=\"utf-8\">"
      "<title>Astro: page assets missing</title>"
      "<body style=\"font:14px system-ui;padding:2rem\">"
      "<h1>This Astro page has no assets to serve.</h1>"
      "<p>The controller for <code>",
      base::EscapeForHTML(host),
      "</code> asked for a file that is not on disk:</p><p><code>",
      base::EscapeForHTML(path.AsUTF8Unsafe()),
      "</code></p>"
      "<p>The page is registered and its controller ran, so this is a "
      "packaging fault, not a routing one: the build did not stage this "
      "page's bundle where the browser reads it.</p>",
  });
}

// THE SEAM.
//
// This is the one function that knows where a page's assets come from, and the
// one thing issue #16 replaces: the resources move into a .pak generated by
// GN/GRIT, and this becomes a resource-id lookup. Nothing else in this file,
// and nothing in any page controller, has to change for that.
//
// Until then assets are read from a directory beside the executable, which
// carries none of Chromium's resource-bundling guarantees — the path is a
// contract with tools/build.sh's staging step that nothing but agreement
// enforces, and an out-of-date executable directory is indistinguishable from
// an out-of-date build.
void ServeAstroWebUIResource(std::string_view host,
                             std::string_view resource_directory,
                             const std::string& requested_path,
                             content::WebUIDataSource::GotDataCallback callback) {
  std::string relative;
  if (!ResolveRequestPath(requested_path, &relative)) {
    LOG(ERROR) << "Astro: refusing WebUI request for '" << requested_path
               << "' on host '" << host << "': not a path inside the page";
    std::move(callback).Run(nullptr);
    return;
  }

  base::FilePath exe_dir;
  if (!base::PathService::Get(base::DIR_EXE, &exe_dir)) {
    LOG(ERROR) << "Astro: cannot locate the executable directory, so host '"
               << host << "' has nowhere to read '" << relative << "' from";
    std::move(callback).Run(nullptr);
    return;
  }

  const base::FilePath directory = exe_dir.AppendASCII("resources")
                                       .AppendASCII(resource_directory);
  base::FilePath file = directory.AppendASCII(relative);

  std::string contents;
  if (!base::ReadFileToString(file, &contents)) {
    // A path with no extension is a client-side route, not a file. Serving the
    // document for it is what makes deep links work.
    const bool is_document =
        relative == kIndexDocument || relative.find('.') == std::string::npos;
    if (is_document) {
      file = directory.AppendASCII(kIndexDocument);
      if (!base::ReadFileToString(file, &contents)) {
        LOG(ERROR) << "Astro: host '" << host << "' has no document to serve. "
                   << "Tried " << file << " for request '" << requested_path
                   << "'. The build did not stage this page's bundle.";
        std::move(callback).Run(base::MakeRefCounted<base::RefCountedString>(
            MissingResourceDocument(host, file)));
        return;
      }
    } else {
      LOG(ERROR) << "Astro: host '" << host << "' cannot read " << file
                 << " for request '" << requested_path << "'";
      std::move(callback).Run(nullptr);
      return;
    }
  }

  std::move(callback).Run(
      base::MakeRefCounted<base::RefCountedString>(std::move(contents)));
}

void ApplyCsp(content::WebUIDataSource* source, const WebUIPageCsp& csp) {
  using network::mojom::CSPDirectiveName;
  const struct {
    CSPDirectiveName directive;
    const char* value;
  } kDirectives[] = {
      {CSPDirectiveName::ScriptSrc, csp.script_src},
      {CSPDirectiveName::StyleSrc, csp.style_src},
      {CSPDirectiveName::ImgSrc, csp.img_src},
      {CSPDirectiveName::FontSrc, csp.font_src},
      {CSPDirectiveName::ConnectSrc, csp.connect_src},
  };
  for (const auto& entry : kDirectives) {
    if (entry.value) {
      source->OverrideContentSecurityPolicy(entry.directive, entry.value);
    }
  }
}

}  // namespace

std::string WebUIOrigin(std::string_view host) {
  return base::StrCat({content::kChromeUIScheme, "://", host});
}

void CreateAstroWebUIDataSource(content::WebUI* web_ui, const WebUIPage& page) {
  content::WebUIDataSource* source = content::WebUIDataSource::CreateAndAdd(
      web_ui->GetWebContents()->GetBrowserContext(), std::string(page.host));

  const std::string host(page.host);
  const std::string resource_directory(page.resource_directory);
  source->SetRequestFilter(
      base::BindRepeating([](const std::string&) { return true; }),
      base::BindRepeating(&ServeAstroWebUIResource, host, resource_directory));

  ApplyCsp(source, page.csp);
}

AstroWebUIPageController::AstroWebUIPageController(content::WebUI* web_ui,
                                                   const WebUIPage& page)
    : content::WebUIController(web_ui) {
  CreateAstroWebUIDataSource(web_ui, page);
}

AstroWebUIPageController::~AstroWebUIPageController() = default;

AstroMojoWebUIPageController::AstroMojoWebUIPageController(
    content::WebUI* web_ui,
    const WebUIPage& page,
    bool enable_chrome_send)
    : ui::MojoWebUIController(web_ui, enable_chrome_send) {
  CreateAstroWebUIDataSource(web_ui, page);
}

AstroMojoWebUIPageController::~AstroMojoWebUIPageController() = default;

}  // namespace astro
