#!/usr/bin/env python3
"""Convert an SVG path into Chromium's .icon command format.

Chromium draws its native UI marks -- the omnibox chip, menu items, the task
manager -- from `.icon` files: a list of drawing commands, not SVG. There is no
converter in the tree, so a brand change that stops at the SVG leaves every
native surface showing the old mark, which is exactly what happened here.

Scope is deliberately narrow: the subset of SVG path syntax the Astro mark uses
(M/m, L/l, H/h, V/v, C/c, Z/z). An unsupported command RAISES rather than being
skipped -- a silently dropped curve produces a plausible-looking icon that is
subtly the wrong shape, and nobody would catch it by eye.
"""

from __future__ import annotations

import argparse
import re
import sys

TOKEN = re.compile(r'([MmLlHhVvCcZz])|(-?\d*\.?\d+(?:[eE][-+]?\d+)?)')


def tokenize(path: str) -> list:
    out = []
    for command, number in TOKEN.findall(path):
        out.append(command if command else float(number))
    return out


def convert(path: str, scale: float) -> list[str]:
    """Emit .icon commands, all coordinates absolute and scaled."""
    tokens = tokenize(path)
    lines: list[str] = []
    i = 0
    x = y = 0.0
    start_x = start_y = 0.0
    command = ''

    def fmt(value: float) -> str:
        scaled = round(value * scale, 2)
        return f'{scaled:g}'

    while i < len(tokens):
        token = tokens[i]
        if isinstance(token, str):
            command = token
            i += 1
            if command in 'Zz':
                lines.append('CLOSE,')
                x, y = start_x, start_y
                continue
        # A repeated coordinate set continues the previous command, except that
        # a repeated moveto becomes a lineto -- per the SVG spec, and getting
        # this wrong turns an outline into a series of disconnected jumps.
        effective = command
        if command == 'M' and lines and lines[-1] != 'CLOSE,':
            pass

        if effective in 'Mm':
            dx, dy = tokens[i], tokens[i + 1]
            i += 2
            x, y = (dx, dy) if effective == 'M' else (x + dx, y + dy)
            start_x, start_y = x, y
            lines.append(f'MOVE_TO, {fmt(x)}, {fmt(y)},')
            command = 'L' if effective == 'M' else 'l'
        elif effective in 'Ll':
            dx, dy = tokens[i], tokens[i + 1]
            i += 2
            x, y = (dx, dy) if effective == 'L' else (x + dx, y + dy)
            lines.append(f'LINE_TO, {fmt(x)}, {fmt(y)},')
        elif effective in 'Hh':
            dx = tokens[i]
            i += 1
            x = dx if effective == 'H' else x + dx
            lines.append(f'LINE_TO, {fmt(x)}, {fmt(y)},')
        elif effective in 'Vv':
            dy = tokens[i]
            i += 1
            y = dy if effective == 'V' else y + dy
            lines.append(f'LINE_TO, {fmt(x)}, {fmt(y)},')
        elif effective in 'Cc':
            values = tokens[i:i + 6]
            i += 6
            if effective == 'C':
                x1, y1, x2, y2, nx, ny = values
            else:
                x1, y1 = x + values[0], y + values[1]
                x2, y2 = x + values[2], y + values[3]
                nx, ny = x + values[4], y + values[5]
            lines.append(f'CUBIC_TO, {fmt(x1)}, {fmt(y1)}, {fmt(x2)}, {fmt(y2)}, '
                         f'{fmt(nx)}, {fmt(ny)},')
            x, y = nx, ny
        else:
            raise SystemExit(
                f'ERROR unsupported path command {effective!r}. This converter '
                f'handles M/L/H/V/C/Z only; add it rather than letting the '
                f'shape come out wrong.')
    return lines


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--path', action='append', required=True,
                        help='an SVG path "d" attribute; repeat for each subpath')
    parser.add_argument('--source-size', type=float, required=True,
                        help='the SVG viewBox edge length')
    parser.add_argument('--canvas', type=int, required=True,
                        help='the .icon canvas size')
    # Chromium's format declares only FILL_RULE_NONZERO, which means even-odd
    # is the default and has no token. Emitting one for it fails the build with
    # `use of undeclared identifier FILL_RULE_EVENODD`.
    parser.add_argument('--fill-rule', default='DEFAULT',
                        choices=['NONZERO', 'DEFAULT'])
    parser.add_argument('--out', required=True)
    args = parser.parse_args(argv[1:])

    scale = args.canvas / args.source_size
    lines = [
        '// Astro product mark. Generated by tools/svg_to_chromium_icon.py',
        '// from branding/product_logo/product_logo.svg. Do not hand-edit:',
        '// regenerate from the vector so the native mark and the WebUI mark',
        '// cannot drift apart.',
        '',
        f'CANVAS_DIMENSIONS, {args.canvas},',
    ]
    if args.fill_rule != 'DEFAULT':
        lines.append(f'FILL_RULE_{args.fill_rule},')
    for path in args.path:
        lines.extend(convert(path, scale))
    lines.append('')

    with open(args.out, 'w', encoding='utf-8') as handle:
        handle.write('\n'.join(lines))
    commands = sum(1 for l in lines if l.endswith(','))
    print(f'  wrote {args.out} ({commands} commands)')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
