#!/usr/bin/env python3
"""Generate the STATIC endpoint inventory for Astro Next (issue #6).

This is not the measured network baseline. It is the list of every host Astro's
own source and patches reference, which is what a measured trace gets compared
*against* — a request to a host in this list is explicable, and one to a host
that is not is the interesting kind of surprise.

The distinction the issue asks for — "distinguish a disabled feature from a
feature whose endpoint was merely broken through domain substitution" — has a
concrete answer in this repository, and it is not the expected one. Domain
substitution has never run (issue #4): its regexes are Python syntax and the old
implementation fed them to `sed`, which rejected every one and had its error
discarded. So no endpoint in Astro has been neutered by substitution, and the
mangled hosts that appear in the inherited patch text (`9oo91e.qjz9zk`,
`ch40m1um.qjz9zk`) are upstream ungoogled-chromium's own already-substituted
patch content, not anything Astro's pipeline produced.

Source and patch text are read from `HEAD` through `committed_state`. A host
somebody added in an uncommitted edit is not a host Astro contacts — it is a
host one machine's build would contact — so it is reported as a working-tree
observation instead of being written into the inventory a measured trace gets
compared against.

Usage:
    inventory_endpoints.py --yaml OUT.yaml --json OUT.json
    inventory_endpoints.py --verify
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from urllib.parse import urlsplit

import committed_state

OVERLAY = "src"
PATCHES = "patches"

URL_RE = re.compile(r"https?://[A-Za-z0-9._~:/?#@!$&*+,;=%-]+")

# ungoogled-chromium's substitution scheme rewrites Google hosts into these
# shapes. Seeing them in inherited PATCH TEXT is upstream's own content.
SUBSTITUTED_MARKER = re.compile(r"\.qjz9zk\b|9oo91e|ch40m1um|95tat1c|f0ntz|ch40me")

# Owning component, derived from where the reference lives.
COMPONENTS = [
    ("src/chrome/browser/oxy/adblock/", "adblock"),
    ("src/chrome/browser/oxy/webui/", "webui"),
    ("src/chrome/browser/oxy/", "oxy-identity"),
    ("patches/astro/", "astro-patch"),
    ("patches/ungoogled/", "ungoogled-patch"),
]


def component_for(relative: str) -> str:
    for prefix, name in COMPONENTS:
        if relative.startswith(prefix):
            return name
    return "other"


def scan(root: str, suffixes: tuple[str, ...]) -> dict[str, dict]:
    hosts: dict[str, dict] = {}
    for relative in committed_state.list_files(root, suffixes):
        # Filter-list data is third-party rule content listing the whole
        # advertising internet; it is not Astro contacting anything.
        if "/adblock/resources/" in relative:
            continue
        try:
            text = committed_state.read_bytes(relative).decode("utf-8")
        except UnicodeDecodeError:
            continue
        for url in URL_RE.findall(text):
            host = urlsplit(url.rstrip("\";'),")).netloc
            if not host:
                continue
            entry = hosts.setdefault(
                host,
                {
                    "host": host,
                    "component": component_for(relative),
                    "references": [],
                    "substituted_shape": bool(SUBSTITUTED_MARKER.search(host)),
                },
            )
            if relative not in entry["references"]:
                entry["references"].append(relative)
    return hosts


def build() -> dict:
    overlay = scan(OVERLAY, (".cc", ".h", ".mojom", ".rs"))
    patches = scan(PATCHES, (".patch",))

    return {
        "tool": "tools/baseline/inventory_endpoints.py",
        "kind": "static-reference-inventory",
        "measured": False,
        "note": (
            "Static. Derived from source and patch text, NOT from a captured "
            "trace. A measured baseline needs a running browser behind a "
            "recorder; tools/baseline/capture-network.sh is that harness and it "
            "refuses to emit a trace it did not record."
        ),
        "overlay_hosts": [overlay[h] for h in sorted(overlay)],
        "patch_hosts": [patches[h] for h in sorted(patches)],
    }


def yaml_escape(value: str) -> str:
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')


def render_yaml(document: dict) -> str:
    """Hand-emitted so the tool needs no PyYAML.

    A generator that cannot run until somebody installs a package is a
    generator that stops being run.
    """
    lines = [
        "# Generated by tools/baseline/inventory_endpoints.py — do not edit by hand.",
        "# Regenerate with: tools/baseline/generate-all.sh",
        "",
        "kind: static-reference-inventory",
        "measured: false",
        "note: >-",
    ]
    for chunk in document["note"].split(". "):
        chunk = chunk.strip()
        if chunk:
            lines.append("  " + chunk + ("." if not chunk.endswith(".") else ""))
    lines.append("")

    for section, key in (("overlay_hosts", "overlay"), ("patch_hosts", "patches")):
        lines.append(f"{key}:")
        if not document[section]:
            lines.append("  []")
            continue
        for entry in document[section]:
            lines.append(f"  - host: {yaml_escape(entry['host'])}")
            lines.append(f"    component: {entry['component']}")
            lines.append(f"    substituted_shape: {str(entry['substituted_shape']).lower()}")
            lines.append("    references:")
            for reference in entry["references"]:
                lines.append(f"      - {yaml_escape(reference)}")
        lines.append("")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--yaml")
    parser.add_argument("--json")
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args(argv[1:])

    committed_state.require_repository()
    document = build()

    observations = committed_state.working_tree_observations([OVERLAY, PATCHES])
    committed_state.report_working_tree_observations(
        "inventory_endpoints.py", observations
    )
    document["working_tree_observations"] = observations

    if args.verify:
        print(
            "endpoints: %d host(s) referenced from the overlay, %d from patches"
            % (len(document["overlay_hosts"]), len(document["patch_hosts"]))
        )
        for entry in document["overlay_hosts"]:
            print(f"  {entry['component']:14} {entry['host']}")

    if args.yaml:
        path = Path(args.yaml)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render_yaml(document), encoding="utf-8")
        print(f"wrote {path}")

    if args.json:
        path = Path(args.json)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as handle:
            json.dump(document, handle, indent=2, sort_keys=True)
            handle.write("\n")
        print(f"wrote {path}")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
