#!/usr/bin/env python3
"""inventory_settings_parity.py — what Chromium's settings page actually is.

Astro is replacing that page with a Vite + Tailwind + Bloom app that keeps only
the API underneath it. "Replacing it 100%" is a claim, and a claim needs a
denominator: this measures the surface from Chromium's own source so progress
is checked rather than asserted.

Three things are counted, because they are three different kinds of work:

  ROUTES        every screen the page can be on. Read from the SettingsRoutes
                interface in router.ts, which is the page's own list.
  HANDLERS      the C++ WebUIMessageHandlers settings_ui.cc installs. This is
                the control surface that exists ONLY as a handler -- search
                engines, site permissions, importing, reset. Astro's page
                inherits all of them (astro_settings_page.h), so these are
                available, not reimplemented.
  PRIVATE APIS  the chrome.*Private APIs the page calls, with call counts.

Nothing here is hand-listed. A route Chromium adds in a roll appears in the
next regeneration as unimplemented, which is the point: the document cannot
quietly fall behind the browser it describes.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

# Site-settings permission subpages are one screen with a different content
# type, not fifty-five screens. Counting them separately makes the work look
# fifty times larger than it is and hides the routes that are genuinely
# distinct, so they are reported as their own group.
SITE_SETTINGS_PREFIX = "SITE_SETTINGS_"


def read_routes(settings_dir: str) -> list[str]:
    path = os.path.join(settings_dir, "router.ts")
    with open(path, encoding="utf-8") as handle:
        source = handle.read()
    match = re.search(r"export interface SettingsRoutes\s*\{(.*?)\n\}",
                      source, re.S)
    if not match:
        raise SystemExit(
            f"ERROR SettingsRoutes not found in {path}.\n"
            f"      The page's own route list has moved; find where it now\n"
            f"      lives rather than falling back to a hand-written list --\n"
            f"      a hand-written denominator is what this tool exists to\n"
            f"      avoid.")
    routes = re.findall(r"^\s{2}([A-Z][A-Z0-9_]*):", match.group(1), re.M)
    if not routes:
        raise SystemExit("ERROR SettingsRoutes matched but declared no routes")
    return sorted(set(routes))


def read_handlers(webui_settings_dir: str) -> list[str]:
    path = os.path.join(webui_settings_dir, "settings_ui.cc")
    with open(path, encoding="utf-8") as handle:
        source = handle.read()
    handlers = re.findall(
        r"AddSettingsPageUIHandler\(\s*std::make_unique<([A-Za-z0-9_:]+)>",
        source)
    handlers += re.findall(
        r"web_ui\(\)->AddMessageHandler\(\s*std::make_unique<([A-Za-z0-9_:]+)>",
        source)
    if not handlers:
        raise SystemExit(
            f"ERROR no handler registrations found in {path}.\n"
            f"      settings_ui.cc registers them some other way now; a zero\n"
            f"      here would report the control surface as empty.")
    return sorted(set(handlers))


def read_private_apis(settings_dir: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    for root, _dirs, files in os.walk(settings_dir):
        for name in files:
            if not name.endswith(".ts"):
                continue
            with open(os.path.join(root, name), encoding="utf-8",
                      errors="replace") as handle:
                for api in re.findall(r"chrome\.([a-zA-Z]+Private)\b",
                                      handle.read()):
                    counts[api] = counts.get(api, 0) + 1
    return dict(sorted(counts.items(), key=lambda kv: -kv[1]))


def render(routes: list[str], handlers: list[str],
           apis: dict[str, int], implemented: set[str]) -> str:
    site_routes = [r for r in routes if r.startswith(SITE_SETTINGS_PREFIX)]
    other_routes = [r for r in routes if not r.startswith(SITE_SETTINGS_PREFIX)]
    done = len(implemented & set(routes))

    lines = [
        "# Settings parity",
        "",
        "GENERATED by tools/baseline/inventory_settings_parity.py. Do not edit:",
        "the next regeneration reverts an edit with no explanation.",
        "",
        "Astro serves its own settings page from a Vite + Tailwind + Bloom app",
        "(`//astro/browser/resources/webui`). Chromium's settings UI is not",
        "reused; its API is. This document is the denominator for \"replaced",
        "100%\" -- measured from Chromium's source, not from a list anyone",
        "maintains.",
        "",
        "## Routes",
        "",
        f"- {len(routes)} declared in `router.ts`",
        f"- {len(site_routes)} of them are `{SITE_SETTINGS_PREFIX}*`: ONE screen",
        "  parameterised by content-setting type, not that many screens",
        f"- {len(other_routes)} distinct screens besides",
        f"- {done} implemented in the Bloom app",
        "",
    ]

    lines.append("### Distinct screens")
    lines.append("")
    for route in other_routes:
        mark = "x" if route in implemented else " "
        lines.append(f"- [{mark}] {route}")
    lines.append("")

    lines.append("### Site-settings permission subpages")
    lines.append("")
    lines.append("One generic screen covers these; each entry is a content type.")
    lines.append("")
    for route in site_routes:
        mark = "x" if route in implemented else " "
        lines.append(f"- [{mark}] {route}")
    lines.append("")

    lines += [
        "## Handlers",
        "",
        "The browser control that exists ONLY as C++. Astro's page derives from",
        "`settings::SettingsUI`, so every one of these is installed and reachable",
        "from the app through `chrome.send` -- verified against `astro://settings`",
        "as a control, not assumed.",
        "",
        f"{len(handlers)} registered:",
        "",
    ]
    lines += [f"- {handler}" for handler in handlers]
    lines.append("")

    lines += [
        "## Private extension APIs",
        "",
        "Call counts in Chromium's settings resources, as a measure of how much",
        "of a section depends on each.",
        "",
    ]
    lines += [f"- `chrome.{api}` — {count} calls" for api, count in apis.items()]
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--chromium-src", required=True)
    parser.add_argument("--implemented", default="",
                        help="comma-separated route names already shipped")
    parser.add_argument("--out", required=True)
    parser.add_argument("--json-out")
    args = parser.parse_args(argv[1:])

    settings_dir = os.path.join(args.chromium_src,
                                "chrome/browser/resources/settings")
    webui_settings_dir = os.path.join(args.chromium_src,
                                      "chrome/browser/ui/webui/settings")
    for path in (settings_dir, webui_settings_dir):
        if not os.path.isdir(path):
            raise SystemExit(
                f"ERROR {path} is missing. This tool measures the real "
                f"Chromium checkout; without it there is nothing to measure "
                f"and an empty inventory would read as \"nothing to do\".")

    routes = read_routes(settings_dir)
    handlers = read_handlers(webui_settings_dir)
    apis = read_private_apis(settings_dir)
    implemented = {r.strip() for r in args.implemented.split(",") if r.strip()}

    unknown = implemented - set(routes)
    if unknown:
        raise SystemExit(
            f"ERROR --implemented names routes that do not exist: "
            f"{', '.join(sorted(unknown))}")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(render(routes, handlers, apis, implemented))

    if args.json_out:
        with open(args.json_out, "w", encoding="utf-8") as handle:
            json.dump({"routes": routes, "handlers": handlers,
                       "private_apis": apis,
                       "implemented": sorted(implemented)}, handle, indent=2)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
